### ISSUE TITLE
Support fixed positioning ad style

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/ethical-ad-client#13]
A user asked for a fixed positioning. They did it in the bottom right, and shared this CSS:

https://github.com/colyseus/docs/blob/8b588a1264154566d11cd6b86e87e064b7778379/docs/stylesheets/ads.css#L25-L33

I think we should probably support a fixed footer as well, similar to JSbin. We already have this on RTD, just need to backport it to the new client.

**Comment by davidfischer** [comment]
This is now supported using the stickybox placement and fixedfooter placements: https://ethical-ad-client.readthedocs.io/en/latest/#placement-style
