### ISSUE TITLE
Ad placement for Read the Docs addons

### ISSUE THREAD

**Issue by humitos** [readthedocs/ethical-ad-client#188]
We merged https://github.com/readthedocs/readthedocs.org/pull/11230 a few days ago. That PR makes the Ad to always (instead of only 25% of times) be displayed at the bottom right.

This placement is a little incompatible with the position of the flyout addons because they collide. Because of that, I suggested to move the ad a few pixels to the top and reduce the `z-index` a little to be shown behind the flyout when it's expanded.

### Example

![Screenshot_2024-02-05_11-25-05](https://github.com/readthedocs/ethical-ad-client/assets/244656/96460272-a5f4-42bd-9079-2045b2b893ce)

I'd like to move forward with this because we are not showing ads currently when projects use the addons, and I don't want to have a lot of users in that state and then from one day to another show ads on all of them.

I'm adding this issue to the roadmap so we can prioritize. Also, I'm not sure _where_ this code has to be written since this may be something special for Read the Docs only. In any case, it would be good to have some pointers to the actual code that's generating this placement that I don't know where it is.

Slack conversation (private): https://readthedocs.slack.com/archives/C029M3W01KR/p1707129461506509

**Comment by humitos** [comment]
> Reducing the z-index seems fine. We do want the ad behind the flyout when it's expanded. We also could increase the flyout z-index.

Yes, definitely. EA `z-index` is already rolled out more broadly than the new beta flyout --so we can easily tweek the flyout one without breaking anything. We may need to also adjust other `z-index` (e.g. search modal) but that's fine.

> We can move the ad up but another possibility is to control the placement somewhat with parameters passed to the ad client through the placement (spitballing here but maybe `data-ea-placement-bottom`). This way we can keep the ad in its position but allow users to control it. Thoughts?

I don't a have ton of context here, so I suppose whatever works best from your side is fine. My original thought was to adjust the positioning on Read the Docs side (since I guess this position is only for Read the Docs publisher, but maybe I'm wrong). In the case this placement is shared among multiple publishers, I think we can:

1. keep the current one as-is and create a new one specific for Read the Docs Addons
2. keep the current one as-is and add the `data-ea-placement-bottom` property you mentioned (more flexible)

Either solution sounds good to me.

Where does the code for the placement lives? Is it on the ad client or on the Read the Docs side?

**Comment by humitos** [comment]
I'd like to move forward with this. @davidfischer What are the next steps here? Would it be useful to jump into a meeting? Otherwise, if you give some directions here I may be able to implement it by myself.

**Comment by davidfischer** [comment]
> I think we should:
> 
> * Increase the `z-index` for the addons flyout to be higher than the ad
> * Increase the `z-index` for the addons search modal to be higher than the addons flyout
> * Add `data-ea-placement-bottom` property to `stickybox` ad style in the EthicalAd js client
> * Inject the `stickybox` ad from addons ethicalads using `data-ea-placement-bottom` with a value making it to display higher than the flyout

This sounds like a plan. I'm going to make sure #190 is merge-ready and get it released. Thanks for jumping in there!
