### ISSUE TITLE
No `alt` on the ad image

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/ethical-ad-client#69]
Got this report from a publisher:

> I have a quick request: the images that EthicalAds injects do not have an alt attribute and this is an accessibility issue (the full URL will be announced instead). Can the code be updated so it at least adds an empty alt attribute (this prevents the image from being announced, which is fine because the text below it does get announced).

We should adapt our `img` tag to have a proper `alt`. Probably something like `Sponsored image` or similar.

**Comment by davidfischer** [comment]
This is a server side setting. I have since added it.
