### ISSUE TITLE
Links to cross-origin destinations are unsafe

### ISSUE THREAD

**Issue by h-enk** [readthedocs/ethical-ad-client#75]
Running Google Lighthouse on a page w/ an EthicalAds ad (e.g. https://getdoks.org/docs/prologue/introduction/), results in:

![Snag_981970](https://user-images.githubusercontent.com/3902872/126293194-e08ff994-c609-4c9f-9157-3eed61264e4d.png)

👉 Would be very nice to have `rel="noopener"` added to the `target="_blank"` links.

**Comment by ericholscher** [comment]
I think `rel="noopener"` is probably the correct solution here. We'll see about getting this added to the client soon. Thanks for filing an issue!

**Comment by davidfischer** [comment]
Just a note that this change will go out in ~24 hours.

**Comment by h-enk** [comment]
Super — thanks!
