### ISSUE TITLE
Add support for fallback ads when nothing available on EA

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/ethical-ad-client#8]
We should allow users to load an additional snippet when we can't serve an ad for them, so they can have carbon or similar as a fallback.

**Comment by ericholscher** [comment]
From a user:

```
I use to have something like this on Codefund, an event telling that there is no ads.

 <script type="text/javascript">
      window.addEventListener("codefund", function(evt) {

        if (evt.detail.status !== "ok") {
          // Render ad from another network
        }
      });
    </script>
```

**Comment by davidfischer** [comment]
This was my idea behind the flag we can have for publishers that only returns paid ads. That way they can fallback to another network if they want.

**Comment by ericholscher** [comment]
@davidfischer right, but we still need a way to tell them to fallback, no?

**Comment by davidfischer** [comment]
Yes.

**Comment by oliviertassinari** [comment]
> I use to have something like this on Codefund, an event telling that there is no ads.

I have the same use case. If there are no paid ads to show, we turn to display our own. I'm not sure to follow how to implement this, looking at the related pull request.

**Comment by ericholscher** [comment]
@oliviertassinari the client can handle this now: https://ethical-ad-client.readthedocs.io/en/latest/#customization -- it's a bit tricky because for testing we're already returning a test ad, but once it's live, it will return a blank ad when there isn't a paid ad, and the logic there checking for no placements should allow handling a fallback.
