### ISSUE TITLE
Static site support using CSS in lieu of JS

### ISSUE THREAD

**Issue by sureshjoshi** [readthedocs/ethical-ad-client#92]
I'm not sure if GH tickets are the right medium for this, but I have a static site blog where I've been experimenting with the location of the ad. 

For desktop, I have the image placed in a column on the right side of the screen, while in mobile, it's a text bar at the bottom of the screen. However, as I don't have any JS running on my screen, all layout manipulation happens via css. 

When I have two ads divs (with only 1 ad ever in display, other other with `display: none`), one of my ads just never loads - the div is always height 0. My guess is because when the Ethical JS loads, it looks for the first appropriate div and tries to populate it and ignores the subsequent one.

For clarity, what I mean is: The mobile text ad shows correctly in a mobile layout, but when I go into a desktop layout, my desktop ad has height 0 (and my mobile ad is technically set as `display: none` - so it correctly doesn't show up).

Is there a non-JS solution to my problem? Or will I need to add some JS to ensure there is only 1 ads div in my DOM at all times?

Thanks!

**Comment by ericholscher** [comment]
@sureshjoshi I'm guessing the main issue is that we're currently only supporting 1 ad load per page on our client. We do have a beta version of our client that supports loading multiple ad placements. It would definitely be best to only have a single placement that uses CSS to move, but I definitely understand not wanting to do that.

You can try out our beta client here: https://media.ethicalads.io/media/client/beta/ethicalads.min.js, and let me know if that works for you.

**Comment by sureshjoshi** [comment]
Thanks @ericholscher - the beta works great!
